### ISSUE TITLE
Invalid Signature even if API keys are correct (using PHP binding) - SOLVED - PLEASE UPDATE YOUR PHP BINDING

### ISSUE THREAD

**Issue by aksharjamgaonkar** [tripit/api#54]
HI Tariq,
 iam getting s:144:"401104.1invalid signature"; error even if iam providiing the correct API key and API Password. My code was working properly few days back but suddenly iam getting this error. Can you please let me know what the issues could be.

Thanks in advance,

**Comment by tariqislam** [comment]
Hi,

Perhaps your server clock is way off? Are you using our PHP API binding? If not, you may want to use that to compare what signature string it outputs to what you generate.

Thanks.

Tariq

**Comment by jpatokal** [comment]
I'm suddenly getting this as well, with code and keys that had worked fine for months before.  Using tripit.php 29011 (the latest).

**Comment by tariqislam** [comment]
Hi guys,

If you have resolved this problem, please let me know what you did to resolve it, so I can recommend that to others in the future.

If you haven't resolved it yet, please send me an email at tariq@tripit.com with the following details:
- Your app's consumer key, and OAuth user token against which you are making API call
- Request url, OAuth signature string
- All request headers
- All response headers
- All response content
- When (date, time, timezone) the request was made (and error seen)
- Anything else that may help me debug

Thanks!

Tariq

**Comment by schofs** [comment]
I'm also having this issue - could it be that the US have changed their clocks but the UK haven't, meaning they're an hour out?

Has been working perfectly for 6 months, and then all of a sudden not working (with no code changes)

I've submitted my details to Tariq

**Comment by tariqislam** [comment]
Hi guys,

Please send me all the information requested above, in order for me to debug this case. Also, please let me know whether this is an intermittent failure, or if every API call being made is failing, and exactly when you first noticed it.

Thanks.

Tariq

**Comment by tariqislam** [comment]
Hi guys,

It seems the issue is on the 'https://api.tripit.com/oauth/request_token' API call, using our PHP library. I'm looking at it and will let you know the outcome.

Thanks.

Tariq

**Comment by tariqislam** [comment]
Hi guys,

The issue has been resolved in our PHP binding -- please update your PHP binding code to the latest in Github:
https://github.com/tripit/php_binding_v1

For a quick reference to the change made for this bug fix, here is the diff:
https://github.com/tripit/php_binding_v1/commit/cdfde7b6433418c74f8f991efa4ef8760f4cb83c

Thanks, and my apologies for this issue.

Best regards,

Tariq

**Comment by jpatokal** [comment]
Sorry, I'm still getting the issue even with the "fixed" version.  Chucking a little debugging in there shows that _do_request is still building busted-looking URLs like `https://api.tripit.com//v1/list/trip` (note //), and that it's failing before it even gets around to calling request_token/access_token.

**Comment by tariqislam** [comment]
Hi Jani,

Are you setting the api url value correctly (without the trailing slash) when you instantiate the TripIt object?

i.e.

``` php
$api_url = 'https://api.tripit.com';     // And not 'https://api.tripit.com/'
$oauth_consumer_key = CONS_KEY;
$oauth_consumer_secret = CONS_SEC;
$oauth_access_token = TOKEN;
$oauth_access_token_secret = SEC;

// Create an OAuth Credential Object
$oauth_cred = new OAuthConsumerCredential($oauth_consumer_key, $oauth_consumer_secret, $oauth_access_token, $oauth_access_token_secret);

// Create a new TripIt object
$t = new TripIt($oauth_cred, $api_url);   // Optionally, you can construct TripIt object without passing an $api_url value, e.g. $t = new TripIt($oauth_cred);
```

**Comment by jpatokal** [comment]
A-ha, that fixed it -- thank you!

**Comment by tariqislam** [comment]
Leaving the issue open so that others can find it easily.

**Comment by tariqislam** [comment]
Closing after inactivity on this issue.
